ecommerce/account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('sign/', views.SignView.as_view(), name="sign"),
    path('logout/', views.logout_view, name="logout"),
    path('settings/', views.SettingsView.as_view(), name="settings"),
]

ecommerce/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


app_name = 'api'

router = routers.SimpleRouter()
router.register(r'product', views.ProductViewSet)
router.register(r'knife', views.KnifeProductView)
router.register(r'melee', views.MeleeProductView)
router.register(r'souvenir', views.SouvenirProductView)
router.register(r'flashlight', views.FlashlightProductView)
router.register(r'accompanying', views.AccompanyingProductView)
router.register(r'orders', views.OrderViewSet, basename='order')

urlpatterns = router.urls

ecommerce/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', 'store')),
    path('account/', include('account.urls', 'account')),
    path('api/', include('api.urls', 'api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Serve Media files

ecommerce/store/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='homepage'),
    path('search/<str:query_string>/', views.SearchProductView.as_view(), name='search'),
    path('products/', views.ProductsView.as_view(), name='products'),
    path('products/<slug:product_type>/', views.CertainProductsView.as_view(), name='certain'),
    path('product/<slug:slug>/', views.ProductView.as_view(), name='product'),
    path('cart/', login_required(views.CartView.as_view()), name='cart'),
    path('favourite/', login_required(views.FavouriteView.as_view()), name='favourite'),
    path('newsletters/', views.NewslettersView.as_view(), name='newsletter'),
    path('success/', views.success_view, name='success'),
    path('failure/', views.failure_view, name='failure'),
]

ecommerce/store/views.py
from django.db.models import PositiveIntegerField
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.utils.text import slugify
from django.views.generic import (
    View,
    TemplateView,
    ListView,
    DetailView,
)
from django.views.generic.base import (
    ContextMixin,
)
from django.http import HttpResponse
from django.contrib.auth.models import AnonymousUser
from django.core.paginator import Paginator

from store.utils import newsletter
from store.models import (
    Product,
    Knife,
    Subcategory,
    Category,
)

from api.serializers import ProductSerializer
import json


# Mixins


# Class Based Views
class HomepageView(TemplateView, ContextMixin):
    template_name = "store/homepage.html"


class NewslettersView(View):
    def post(self, request, *args, **kwargs):
        if request.POST.get('action') == 'sign':
            newsletter.sign(request.GET.get('email'))
        elif request.POST.get('action') == 'unsign':
            newsletter.unsign(request.GET.get('email'))
        return HttpResponse('success')


class ProductsView(TemplateView):
    template_name = 'store/products.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'prods_cat': self.model.__name__,
            'filter_cats': Category.objects.all(),
            'max_price': int(self.model.objects.all().order_by('-price')[0].price)+1 if self.model.objects.all().count() > 0 else None,
            'min_price': int(self.model.objects.all().order_by('price')[0].price)    if self.model.objects.all().count() > 0 else None,
            'api_url': f'/api/{slugify(self.model.__name__)}/', # Set API url depending on self.model
            'orderings': {
                '-created_at': "Newer",
                'created_at': "Older",
                '-price': "Higher price",
                'price': "Lower price",
                '-rating': "Higher rating",
                'rating': "Lower rating",
                '-sold': "Most popular",
                'sold': "Least popular",
            }
        })
        return context
    

class CertainProductsView(ProductsView):

    def get(self, request, product_type, *args, **kwargs):
        subs = list(filter(lambda cls: slugify(cls.__name__) == product_type, Product.__subclasses__())) # See if product_type is in list of Product child subclasses
        self.model = subs[0] if len(subs) > 0 else None
        if not self.model: # Raise 404 if product_type not found
            return HttpResponse(status=404)
        return super().get(request, *args, **kwargs)
    
    def get_range_filters(self):
        model_fields = self.model._meta.fields
        field_dicts = []
        forbidden_field_names = ['rating', 'in_stock', 'sold', 'bonus_points']
        for field in model_fields:
            if isinstance(field, PositiveIntegerField) and field.name not in forbidden_field_names and self.model.objects.all().count() > 0:
                max_value = getattr(self.model.objects.all().order_by('-'+field.name)[0], field.name)
                min_value = getattr(self.model.objects.all().order_by(field.name)[0], field.name)
                field_dict = {
                    'title': field.name.replace('_', ' '),
                    'param_name': field.name + '_gap',
                    'max': max_value,
                    'min': min_value
                }
                field_dicts.append(field_dict)
        return field_dicts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'supercategory': self.model,
            'supercategory_title': self.model.__name__,
            'filter_cats': self.model.get_type_cats(),
            'range_filters': self.get_range_filters(),
        })
        return context


class ProductView(DetailView):
    model = Product
    template_name = "store/product.html"    
    context_object_name = "product"

    def get_context_data(self, object, *args, **kwargs):
        context = super().get_context_data()
        Supercat: Product = object.__class__
        cats = list(object.cats.all())
        subcats = object.subcats.all()
        context.update({
            'supercat': {
                'name': Supercat.__name__,
                'url': Supercat.get_absolute_url_to_type() if issubclass(Supercat, Product) else '/products/',
            },
            'personal_rating': int(object.votes.filter(user=self.request.user)[0].value) if object.votes.filter(user=self.request.user) else None,
            'in_fav': self.request.user.favourite.products.filter(id=object.id).exists() if self.request.user.is_authenticated else None,
            'in_cart': self.request.user.cart.get_products().filter(id=object.id).exists() if self.request.user.is_authenticated else None,
            'manufacturer': object.subcats.get(cat__title="manufacturer") if object.cats.filter(title="manufacturer").exists() else None,
            'series': object.subcats.get(cat__title="series") if object.cats.filter(title="series").exists() else None,
            'cats': list(map(lambda cat: (cat.title, cat.get_subcats(subcats=subcats)), cats)),
            'properties': object.get_properties(),
        })
        return context


class SearchProductView(ProductsView):

    def get(self, request, query_string, *args, **kwargs):
        self.query_string = query_string
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["api_url"] = context["api_url"] + "search/" + self.query_string
        return context
    

class ProductContainerView(TemplateView, ContextMixin):
    """ Anscestor for the views ment to show products in a product container such as Cart or Favourite. """
    template_name = 'store/product_container.html'


class CartView(ProductContainerView):

    def get_context_data(self):
        return {
            'container_name' : 'cart',
            'in_container' : self.request.user.get_cart_count() if self.request.user.is_authenticated else False,
            'products': self.request.user.cart.get_products() if self.request.user.is_authenticated else None,
        }


class FavouriteView(ProductContainerView):

    def get_context_data(self):
        return {
            'container_name' : 'favourite',
            'in_container' : self.request.user.get_favourite_count() if self.request.user.is_authenticated else False,
            'products': self.request.user.favourite.products.all() if self.request.user.is_authenticated else None,
        }


# Function Based Views
def success_view(request):
    return render(request, 'store/success.html')

def failure_view(request):
    return render(request, 'store/failure.html')
    

ecommerce/store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'fontawesomefree/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesomefree/js/all.js' %}">
    <link rel="shortcut icon" href="{% static 'store/images/icons/favicon.svg' %}" type="image/x-icon">
    <title>{% block title %}{% endblock title %} | ZlatMax</title>
    {% block extra_head %}
    {% endblock extra_head %}
</head>
<body>
    <div class="load column">
        <div class="load__container">
            <div class="load__ring_orange load__ring circle"></div>
            <div class="load__ring_black load__ring circle"></div>
            <div class="load__ring_green load__ring circle"></div>
        </div> 
    </div>
    <script src="{% static 'store/scripts/onload.js' %}"></script>
    {% block body %}
        
    {% endblock body %}
    {% include 'store/templates.html' %}
</body>
</html>

ecommerce/store/templates/store/failure.html
{% extends "store/base.html" %}
{% load static sass_tags %}
{% block title %}Payment Failure{% endblock title %}
{% block extra_head %}
    <link rel="stylesheet" href="{% sass_src 'store/styles/pay_status.scss' %}">
    <meta http-equiv="refresh" content="7; url='{% url 'store:cart' %}'" />
{% endblock extra_head %}
{% block body %}
    <div class="wrapper">
        <main class="content column flex-center">
            <div class="face circle">
                <div class="face-container">
                    <div class="eyes row flex-center">
                        <div class="eyes__left failure"></div>
                        <div class="eyes__right failure"></div>
                        <div class="x-mark__left failure"></div>
                        <div class="x-mark__right failure"></div>
                    </div>
                    <div class="mouth"></div>
                </div>
                <div class="sign-container">
                    <div class="sign"></div>
                </div>
            </div>
            <h1>Something went wrong and payment ended up as a failure!</h1>
            <p>Soon you'll be automatically redirected to <a href="{% url 'store:cart' %}" class="link">Cart.</a></p>
        </main>
    </div>
{% endblock %}

ecommerce/store/templates/store/footer.html
{% load static %}
<footer class="page-footer">
    <div class="page-footer__container column">
        <section class="page-footer__floor page-footer__floor_1">
            <ul class="page-footer__items row">
                <li class="page-footer__item column">
                    <h1 class="page-footer__item-title">Information</h1>
                    <h2 class="page-footer__item-link"><a href="#">ZLATMAX in Germany</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">Knives steel</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">About us</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">Payment and delivery terms</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">Confidence policy</a></h2>
                </li>
                <li class="page-footer__item column">
                    <h1 class="page-footer__item-title">Support</h1>
                    <h2 class="page-footer__item-link"><a href="#">Contacts</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">Return product</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">Site map</a></h2>
                </li>
                <li class="page-footer__item column">
                    <h1 class="page-footer__item-title">Additional information</h1>
                    <h2 class="page-footer__item-link"><a href="#">Gift cards</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">Partner information</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">On sale</a></h2>
                </li>
                <li class="page-footer__item column">
                    <h1 class="page-footer__item-title">Personal account</h1>
                    <h2 class="page-footer__item-link"><a href="{% url 'account:settings' %}">Personal account</a></h2>
                    <h2 class="page-footer__item-link"><a href="#">Order history</a></h2>
                    <h2 class="page-footer__item-link"><a href="{% url 'store:favourite' %}">Favorite</a></h2>
                    <h2 class="page-footer__item-link"><a href="#newsletter-email">Sign newsletter</a></h2>
                </li>
            </ul>
        </section>
        <hr class="page-footer__line">
        <section class="page-footer__floor page-footer__floor_2">
            <ul class="page-footer__items row">
                <li class="page-footer__item column">
                    <h1 class="page-footer__item-title">Contacts</h1>
                    <h2 class="page-footer__item-link"><a href="#">
                        <img src="{% static 'store/images/icons/phone-icon.svg' %}" alt="call"> +49 152 901820
                    </a></h2>
                    <h2 class="page-footer__item-link"><a href="#">
                        <img src="{% static 'store/images/icons/clock-icon.svg' %}" alt="time"> Mon-Fri 7:00 - 16:00 (GMT+2)
                    </a></h2>
                    <h2 class="page-footer__item-link"><a href="#">
                        <img src="{% static 'store/images/icons/location-icon-white.svg' %}" alt="location" height="20"> Berlin, Examplestraße 1A
                    </a></h2>
                    <h2 class="page-footer__item-link"><a href="#">
                        <img src="{% static 'store/images/icons/mail-icon.svg' %}" alt="mail"> example@mail.com
                    </a></h2>
                    <ul class="page-footer__socials row">
                        <li class="page-footer__social"><a href="#"><img src="{% static 'store/images/icons/facebook.png' %}" alt="facebook link"></a></li>
                        <li class="page-footer__social"><a href="#"><img src="{% static 'store/images/icons/viber.png' %}" alt="viber link"></a></li>
                        <li class="page-footer__social"><a href="#"><img src="{% static 'store/images/icons/telegram.png' %}" alt="telegram link"></a></li>
                        <li class="page-footer__social"><a href="#"><img src="{% static 'store/images/icons/whatsapp.png' %}" alt="whatsapp link"></a></li>
                    </ul>
                </li>
                <li class="page-footer__item column">
                    <h1 class="page-footer__item-title">Useful links</h1>
                    <h2 class="page-footer__item-link"><a href="#">Methods to pay and deliver</a></h2>
                </li>
                <li class="page-footer__item column">
                    <h1 class="page-footer__item-title">Waranty</h1>
                    <p class="page-footer__item-link">Unsutisfied with your purchase? You can return it until 30 days since the day of recieving, ruling by <a href="#">our rules</a></p>
                </li>
                <li class="page-footer__item column">
                    <h1 class="page-footer__item-title">Newsletter</h1>
                    <h2 class="page-footer__item-link"><a href="#newsletter-email">Sign up now!</a></h2>
                    <div class="page-footer__newsletter row">
                        <div class="newsletter-container row">
                            <input type="email" class="newsletter-email" id="newsletter-email" title="Make sure your EMAIL is similar to example!" pattern="[A-Za-z0-9._+-]+@[A-Za-z0-9 -]+\.[a-z]{2,}" placeholder="example@gmail.com" {% if request.user.is_authenticated %}value="{{request.user.email}}"{% endif %} />
                            <button class="newsletter-button newsletter-button_sign"><img src="{% static 'store/images/icons/arrow-icon.svg' %}" alt="arrow"></button>
                            <button class="newsletter-button newsletter-button_unsign toggled"><img src="{% static 'store/images/icons/arrow-icon.svg' %}" alt="arrow"></button>
                            <button class="newsletter-toggler pushable"><img src="{% static 'store/images/icons/reverse-icon.svg' %}" alt="toggle signing"></button>
                        </div>
                    </div>
                </li>
            </ul>
        </section>
        <hr class="page-footer__line">
        <section class="page-footer__floor page-footer__floor_3">
            <ul class="page-footer__items row">
                <li class="page-footer__item column">
                    <p>All materials posted on the site are for reference only and are not a public offer. When copying materials, a hyperlink to ZLATMAX is required.</p>
                </li>
                <li class="page-footer__item column">
                    <p>ZLATMAX knives www.zlatmax.com ©</p>
                </li>
            </ul>
        </section>
    </div>
</footer>

ecommerce/store/templates/store/header.html
{% load static store_tags %}
<header class="page-header column">
    <section class="page-header__floor_black page-header__floor row">
        <nav class="page-header__navigation row">
            <a href="#" class="link">
                <h1>About us</h1>
            </a>
            <a href="#" class="link">
                <h1>Payment and delivery</h1>
            </a>
            <a href="#" class="link">
                <h1>News board</h1>
            </a>
            <a href="#" class="link">
                <h1>Contacts</h1>
            </a>
            <a href="{% url 'store:products' %}" class="link link_products">
                <h1>Products</h1>
            </a>
        </nav>
        <div class="page-header__personal-profile row">
            <a href="{% url 'account:settings' %}" class="pushable row">
                <img src="{% static 'store/images/icons/user-icon.svg' %}" alt="profile account" class="profile-icon profile-icon_white">
                <h1>Personal account</h1>
            </a>
        </div>
    </section>
    <section class="page-header__floor_white page-header__white page-header__floor row">
        <div class="page-header__white-left row">
            <div class="page-header__logo">
                <a href="/">
                    <img src="{% static 'store/images/logo.svg' %}" alt="ZLATMAX logo">
                </a>
            </div>
            <label class="page-header__product-search-container row" for="search-products">
                <img src="{% static 'store/images/icons/dandruff-icon.svg' %}" alt="product search icon">
                <input 
                    type="text" id="search-products" 
                    class="product-search page-header__product-search" 
                    placeholder="Search for product"
                    list="product-search-suggestions"
                />
                <datalist id="product-search-suggestions">
                </datalist>
            </label>
        </div>
        <div class="page-header__white-right row">
            <ul class="page-header__actions row">
                <li class="page-header__action_location page-header__action row">
                    <a target="_blank" href="https://goo.gl/maps/XaNopbtwZVugYkv99"><img class="location" src="{% static 'store/images/icons/location-icon.svg' %}" alt="location icon"></a>
                    <h1 class="city"><a target="_blank" href="https://goo.gl/maps/XaNopbtwZVugYkv99">Berlin</a></h1>
                </li>
                <li class="page-header__action_phone page-header__action column">
                    <p class="number">+49 152 901820</p>
                    <p class="order-it"><a href="tel:+49152901820">Order by call</a></p>
                </li>
                <li class="page-header__action_buttons page-header__action row">
                    <a href="{% url 'store:favourite' %}" class="pushable favourite-btn"></a>
                    <a href="{% url 'store:cart' %}" class="pushable cart-btn" purchase-count="{% if request.user.is_authenticated %}{{request.user.get_cart_count}}{% else %}0{% endif %}"></a>
                    <div class="column">
                        <p class="summary"><span id="purchase-summary">{% if request.user.is_authenticated %}{{request.user.get_payment_price}}{% else %}0{% endif %}</span>€</p>
                        <a href="#" class="commiting">Commit purchase</a>
                    </div>
                </li>
            </ul>
        </div>
    </section>
    <section class="page-header__floor_cats page-header__floor_black page-header__floor row">
        <ul class="page-header__supercategories row">
            {% for key, supercat in supercategories.items %}
            <li class="page-header__supercategory">
                <details class="page-header__supercategory-details">
                    <summary class="link">
                        <h1>{{key}}</h1>
                    </summary>
                    <ul class="page-header__categories row">
                        {% for cat in supercat.get_type_cats %}
                        <li class="page-header__category column">
                            <h2 class="page-header__category-title"><a class="link" href="{{cat.get_absolute_url}}">{{cat.title}}</a></h2>
                            <hr class="page-header__category-line">
                            <ul class="page-header__subcategories column">
                            {% get_subcats cat as subcats %}
                            {% for subcat in subcats %}
                                <li class="page-header__subcategory">
                                    <h3><a class="link" href="{{subcat.get_absolute_url}}">{{subcat.title}}</a></h3>
                                </li>
                            {% endfor %}
                            </ul>
                            <hr class="page-header__category-line">
                            <h3><a class="link page-header__supercategory-more" href="{{supercat.get_absolute_url_to_type}}">See more</a></h3>
                        </li>
                        {% endfor %}
                    </ul>
                </details>
            </li>
            {% endfor %}
        </ul>
    </section>
</header>
<script>
    const searchInput = document.querySelector('#search-products');
    searchInput.addEventListener('keypress', function (e) {
        if (e.key === 'Enter') {
            window.location.href = location.protocol+"//"+location.host+"/search/"+searchInput.value;
        }
    });
    
</script>

ecommerce/store/templates/store/product_container.html
{% extends "store/base.html" %}
{% comment %} Template for ProductContainer View {% endcomment %}
{% load static sass_tags %}
{% block title %}{{container_name | title}}{% endblock title %}
{% block extra_head %}
<link rel="stylesheet" href="{% sass_src 'store/styles/product_container.scss' %}">
{% endblock extra_head %}
{% block body %}
<div class="wrapper column invisible">
    <!-- Header -->
    <header class="subheader column">
        <div class="row">
            <h1 class="container-title">The {{container_name|title}}</h1>
        </div>
        <div class="row">
            <div class="hierarchy-links row">
                <a href="{% url 'store:homepage' %}">Homepage</a>
                <a class="current" onclick="location.reload();" href="#">{{container_name | title}}</a>
            </div>
            <div class="in-container"><span>{{in_container}}</span> items in {{container_name}}</div>
        </div>
    </header>
    <!-- End Header -->

    <!-- Product List -->
    <section class="section_products">
        <ul class="products column">
            {% for product in products %}
            <li class="product row">
                <div class="column_left row flex-center">
                    <div class="thumbnail row">
                        <a href="{{product.get_absolute_url}}" target="_blank">
                            <img src="{% if product.image_general %}{{product.image_general.url}}{% else %}{% static 'store/images/icons/loading.gif' %}{% endif %}" alt="Product image" />
                        </a>
                    </div>
                    <div class="detail column">
                        <div class="name"><a href="{{product.get_absolute_url}}">{{ product.title }}</a></div>
                        <div class="description">{{ product.description }}</div>
                        <div class="price-container"><span class="price">{{ product.price }}</span>€</div>
                        <input type="hidden" name="id" value="{{product.pk}}">
                        <input type="hidden" name="inStock" value="{{product.in_stock}}">
                    </div>
                </div>

                <div class="column_right row flex-center">
                    <div class="quantity">
                        <input type="number" class="quantity" step="1" value="1" min="1" max="{{product.in_stock}}" />
                    </div>
                    <button class="remove" onclick="removeFromContainer(this)">
                        <svg version="1.1" class="close" xmlns="//www.w3.org/2000/svg"
                            xmlns:xlink="//www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 60 60"
                            enable-background="new 0 0 60 60" xml:space="preserve">
                            <polygon
                                points="38.936,23.561 36.814,21.439 30.562,27.691 24.311,21.439 22.189,23.561 28.441,29.812 22.189,36.064 24.311,38.186 30.562,31.934 36.814,38.186 38.936,36.064 32.684,29.812">
                            </polygon>
                        </svg>
                    </button>
                </div>
            </li>
            {% empty %}
            <h1 class="products__empty">There is no any products yet, <a class="link"
                    href="{% url 'store:products' %}">include some in</a><br><a class="link"
                    href="{% url 'store:homepage' %}">Go Home</a></h1>
            {% endfor %}
        </ul>
    </section>
    <!-- End Product List -->
    <section>
        <hr class="page-divider">
    </section>
    {% if container_name == 'cart' %}
    <!-- Summary -->
    <section class="section_summary row">
        <div class="promotion column">
            <label for="promo-code">Have A Promo Code?</label>
            <div class="row">
                <input placeholder="XXXX-XXXX-XXXX-XXXX" type="text" id="promo-code" />
                <button type="button"></button>
            </div>
        </div>

        <div class="summary column">
            <div class="total row">
                <h1>Total:</h1>
                <p><span>{{request.user.get_payment_price}}</span>€</p>
            </div>
            <div class="checkout">
                <div id="paypal-button-container"></div>
            </div>
        </div>
    </section>
    {% csrf_token %}
    <script src="https://www.paypal.com/sdk/js?client-id=AaxWEpI_8SlfpzmMGkzNgSyhRv2Joz30mBlxzrsLCf6-i8QWLoEaCcDPkIHbButwaOgBPr2tfG01bzw8&currency=EUR&merchant-id=sb-dnffa25818452@business.example.com"></script>
    <script src="{% static 'store/scripts/cart_container.js' %}"></script>
    <!-- End Summary -->
    {% endif %}
</div>
<script>
    const removeFromContainer = btn => {
        " use non-strict "
        let csrf = new DOMParser().parseFromString(`{% csrf_token %}`, 'text/html').querySelector('input').value;
        let id = btn.parentElement.parentElement.querySelector('input[name="id"]').value;
        const response = fetch(`/api/product/${id}/toggle-{{container_name}}/`, {
            method: "POST",
            headers: {'X-CSRFToken': csrf, "Content-Type": "application/json"},
            body: JSON.stringify({'action': 'remove'}),
        })
        let span = document.querySelector('.in-container span');
        span.textContent = Number(span.textContent) - 1;
        span = document.querySelector('.total span'),
            span.textContent = (Number(span.textContent) - Number(btn.parentElement.parentElement.querySelector('.price').textContent)).toFixed(2);
        btn.parentElement.parentElement.remove();
        {% if container_name == 'cart' %}
        if (document.querySelector('.products').children.length === 0) {
            let container = document.querySelector('#paypal-button-container');
            console.log(container);
            container.style.opacity = 0.75;
            container.style.pointerEvents = 'none';
        }
        {% endif %}
    }
</script>
{% endblock body %}

ecommerce/store/templates/store/success.html
{% extends "store/base.html" %}
{% load static sass_tags %}
{% block title %}Payment Success{% endblock title %}
{% block extra_head %}
    <link rel="stylesheet" href="{% sass_src 'store/styles/success.scss' %}">
    <meta http-equiv="refresh" content="7; url='{% url 'store:homepage' %}'" />
{% endblock extra_head %}
{% block body %}
    <div class="wrapper">
        <main class="content column flex-center">
            <div class="face circle">
                <div class="face-container">
                    <div class="eyes row flex-center">
                        <div class="eyes__left"></div>
                        <div class="eyes__right"></div>
                    </div>
                    <div class="mouth"></div>
                </div>
                <div class="check-container">
                    <svg class="check" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8"/></svg>
                </div>
            </div>
            <h1>Thank you very much for your sincere support!</h1>
            <p>Soon you'll be automatically redirected to <a href="{% url 'store:homepage' %}" class="link">Homepage.</a></p>
        </main>
    </div>
{% endblock %}